global:
  scrape_interval: 15s  # Default scrape interval

scrape_configs:
  - job_name: "fake_store_api"
    static_configs:
      - targets: ["fake_store_api:4000"]  # Replace with your API's address
